const PRODUCT_LIST_LOAD_START = 'PRODUCT_LIST_LOAD_START';
const PRODUCT_LIST_LOAD_SUCCESS = 'PRODUCT_LIST_LOAD_SUCCESS';
const PRODUCT_DETAILS_LOAD_START = 'PRODUCT_DETAILS_LOAD_START';
const PRODUCT_DETAILS_LOAD_SUCCESS = 'PRODUCT_DETAILS_LOAD_SUCCESS';

const PRODUCT_RESET = 'PRODUCT_RESET';

export {
  PRODUCT_LIST_LOAD_START,
  PRODUCT_LIST_LOAD_SUCCESS,
  PRODUCT_DETAILS_LOAD_START,
  PRODUCT_DETAILS_LOAD_SUCCESS,
  PRODUCT_RESET,
};
